# Build step #1: build the React front end
FROM node:16-alpine as build-step
WORKDIR /frontend
ENV PATH /frontend/node_modules/.bin:$PATH
COPY /frontend/package.json ./
COPY ./frontend/src ./src
COPY ./frontend/public ./public
RUN yarn install
RUN yarn build

# start app
EXPOSE 5000
CMD ["yarn", "start"]